# Create a GUI Application of Employee Record::
# 1.Creating a window
from tkinter import *
root = Tk()
# creating function / logic
def E_Details():
    Name = str(E_N.get())
    rEn.set(Name)
    EID = int(E_I.get())
    rIn.set(EID)
    EPH = int(ph_num.get())
    rPn.set(EPH)
    E_Mail = str(E_Email.get())
    rEI.set(E_Mail)
    E_dep = str(E_D.get())
    rEd.set(E_dep)
    E_Exp = int(E_E.get())
    rEe.set(E_Exp)
    E_EDU = str(E_Edu.get())
    rEdu.set(E_EDU)
    E_Add = str(E_A.get())
    rEa.set(E_Add)
    # for paid salary on Jan:
    m1s = float(E_JAN_S.get())
    m1l = int(E_JAN_L.get())
    m1pt = float(E_JAN_PT.get())
    P_JAN_SAL = m1s - ((m1s / 30 * m1l) + m1pt)
    PJANSE = round(P_JAN_SAL, 2)
    PJS.set(PJANSE)
    # PJS.set(P_JAN_SAL)

    # for paid salary on Feb:
    m2s = float(E_FEB_S.get())
    m2l = int(E_FEB_L.get())
    m2pt = float(E_FEB_PT.get())
    P_FEB_SAL = m2s - ((m2s / 30 * m2l) + m2pt)
    PFESE = round(P_FEB_SAL, 2)
    PFS.set(PFESE)

    # PFS.set(P_FEB_SAL)

    # for paid salary on Mar:
    m3s = float(E_MAR_S.get())
    m3l = int(E_MAR_L.get())
    m3pt = float(E_MAR_PT.get())
    P_MAR_SAL = m3s - ((m3s / 30 * m3l) + m3pt)
    PMASE = round(P_MAR_SAL, 2)
    PMAS.set(PMASE)
    # for paid salary on Apr:
    m4s = float(E_APR_S.get())
    m4l = int(E_APR_L.get())
    m4pt = float(E_APR_PT.get())
    P_APR_SAL = (m4s - (m4s / 30 * m4l + m4pt))
    PAPRSE = round(P_APR_SAL, 2)
    PAPS.set(PAPRSE)
    # PAPS.set(P_APR_SAL)
    # for paid salary on May:
    m5s = float(E_MAY_S.get())
    m5l = int(E_MAY_L.get())
    m5pt = float(E_MAY_PT.get())
    P_MAY_SAL = (m5s - (m5s / 30 * m5l + m5pt))
    PMAYSE = round(P_MAY_SAL, 2)
    PMYS.set(PMAYSE)
    # PMYS.set(P_MAY_SAL)
    # for paid salary on June:
    m6s = float(E_JUN_S.get())
    m6l = int(E_JUN_L.get())
    m6pt = float(E_JUN_PT.get())
    P_JUN_SAL = (m6s - (m6s / 30 * m6l + m6pt))
    PJUNSE = round(P_JUN_SAL, 2)
    PJUS.set(PJUNSE)
    # PJUS.set(P_JUN_SAL)
    # for paid salary on July:
    m7s = float(E_JUL_S.get())
    m7l = int(E_JUL_L.get())
    m7pt = float(E_JUL_PT.get())
    P_JUL_SAL = (m7s - (m7s / 30 * m7l + m7pt))
    PJULSE = round(P_JUL_SAL, 2)
    PJYS.set(PJULSE)
    # PJYS.set(P_JUL_SAL)
    # for paid salary on Aug:
    m8s = float(E_AUG_S.get())
    m8l = int(E_AUG_L.get())
    m8pt = float(E_AUG_PT.get())
    P_AUG_SAL = (m8s - (m8s / 30 * m8l + m8pt))
    PAUGSE = round(P_AUG_SAL, 2)
    PAS.set(PAUGSE)
    # PAS.set(P_AUG_SAL)
    # for paid salary on Sep:
    m9s = float(E_SEP_S.get())
    m9l = int(E_SEP_L.get())
    m9pt = float(E_SEP_PT.get())
    P_SEP_SAL = (m9s - (m9s / 30 * m9l + m9pt))
    PSEPSE = round(P_SEP_SAL, 2)
    PSS.set(PSEPSE)
    # PSS.set(P_SEP_SAL)
    # for paid salary on Oct:
    m10s = float(E_OCT_S.get())
    m10l = int(E_OCT_L.get())
    m10pt = float(E_OCT_PT.get())
    P_OCT_SAL = (m10s - (m10s / 30 * m10l + m10pt))
    POCTSE = round(P_OCT_SAL, 2)
    POS.set(POCTSE)
    # POS.set(P_OCT_SAL)
    # for paid salary on Nov:
    m11s = float(E_NOV_S.get())
    m11l = int(E_NOV_L.get())
    m11pt = float(E_NOV_PT.get())
    P_NOV_SAL = (m11s - (m11s / 30 * m11l + m11pt))
    PNOVSE = round(P_NOV_SAL, 2)
    PNS.set(PNOVSE)
    # PNS.set(P_NOV_SAL)
    # for paid salary on Dec:
    m12s = float(E_DEC_S.get())  # dec s-> entry->disp-> store->m12s->
    m12l = int(E_DEC_L.get())
    m12pt = float(E_DEC_PT.get())
    P_DEC_SAL = (m12s - (m12s / 30 * m12l + m12pt))
    PDECSE = round(P_DEC_SAL, 2)
    PDS.set(PDECSE)
    # PDS.set(P_DEC_SAL)

    TFA = (m1s + m2s + m3s + m4s + m5s + m6s + m7s + m8s + m9s + m10s + m11s + m12s)
    rTFA.set(TFA)

    TL = (m1l + m2l + m3l + m4l + m5l + m6l + m7l + m8l + m9l + m10l + m11l + m12l)
    rTL.set(TL)

    TPT = (m1pt + m2pt + m3pt + m4pt + m5pt + m6pt + m7pt + m8pt + m9pt + m10pt + m11pt + m12pt)
    rTPT.set(TPT)

    TPS = (
                P_JAN_SAL + P_FEB_SAL + P_MAR_SAL + P_APR_SAL + P_MAY_SAL + P_JUN_SAL + P_JUL_SAL + P_AUG_SAL + P_SEP_SAL + P_OCT_SAL + P_NOV_SAL + P_DEC_SAL)
    rTPS.set(TPS)
    # if salary is in between 500000 to 1000000 TDS=5%:
    if TFA >= 500000.00 and TFA <= 1000000.00:
        tdp = "5%"
        t = 5
        TDSP.set(tdp)
        TDS_A = ((t * TFA) / 100)
        TDSA.set(TDS_A)
    # if salary is in between 1000000 to 15000000 TDS=10%:
    elif TFA >= 1000000.00 and TFA <= 1500000.00:
        tdp = "10%"
        t = 10
        TDSP.set(tdp)
        TDS_A = ((t * TFA) / 100)
        TDSA.set(TDS_A)
    # if salary is in between 1500000 to 2000000 TDS=15%:
    elif TFA >= 1500000.00 and TFA <= 2000000.00:
        tdp = "15%"
        t = 15
        TDSP.set(tdp)
        TDS_A = ((t * TFA) / 100)
        TDSA.set(TDS_A)
    # if salary is in between 2000000 to 3000000 TDS=20%:
    elif TFA >= 2000000.00 and TFA <= 3000000.00:
        tdp = "20%"
        t = 20
        TDSP.set(tdp)
        TDS_A = ((t * TFA) / 100)
        TDSA.set(TDS_A)
    # if salary is above 3000000 then TDS=30%:
    elif TFA >= 3000000.00:
        tdp = "30%"
        t = 30
        TDSP.set(tdp)
        TDS_A = ((t * TFA) / 100)
        TDSA.set(TDS_A)
    # if salary is less than 500000 then TDS="0":
    elif TFA < 500000.00:
        tdp = "NIL"
        TDSP.set(tdp)
        TDS_A = "0"
        TDSA.set(TDS_A)
    # 2.Creating window size and title

root.title("Employee Record Management")
root.geometry("1920x1080")
# result functions of details:
rEn = StringVar()
rIn = StringVar()
rPn = StringVar()
rEI = StringVar()
rEd = StringVar()
rEe = StringVar()
rEdu = StringVar()
rEa = StringVar()
rTFA = StringVar()
rTL = StringVar()
rTPT = StringVar()
rTPS = StringVar()
# Month wise salary paid string declarations:
PJS = StringVar()
PFS = StringVar()
PMAS = StringVar()
PAPS = StringVar()
PMYS = StringVar()
PJUS = StringVar()
PJYS = StringVar()
PAS = StringVar()
PSS = StringVar()
POS = StringVar()
PNS = StringVar()
PDS = StringVar()
# TDS percentage
TDSP = StringVar()
# TDS amount:
TDSA = StringVar()
# 3.Creating window label for entering employee details
Label(root, text="Enter Employee Full Name:").place(x=4, y=4)
Label(root, text="Enter Employee Phone Number:").place(x=4, y=24)  # 28/3=9.50->10        200->x=200 3letters=20 px
Label(root, text="Enter Employee Department:").place(x=4, y=44)
Label(root, text="Enter Employee Experience:").place(x=4, y=64)
Label(root, text="Enter Employee ID:").place(x=400, y=4)  # 19/3=6.5->7     7*20=140
Label(root, text="Enter Employee Email:").place(x=400, y=24)
Label(root, text="Enter Employee Address : ").place(x=400, y=44)
Label(root, text="Enter Employee Education:").place(x=400, y=64)
# Employee Salary month wise
Label(root, text="Enter Jan Salary Amount: ").place(x=4, y=150)  # 25/3->8*20=160
Label(root, text="Enter Feb Salary Amount: ").place(x=4, y=170)
Label(root, text="Enter March Salary Amount: ").place(x=4, y=190)
Label(root, text="Enter April Salary Amount: ").place(x=4, y=210)
Label(root, text="Enter May Salary Amount: ").place(x=4, y=230)
Label(root, text="Enter June Salary Amount: ").place(x=4, y=250)
Label(root, text="Enter July Salary Amount: ").place(x=4, y=270)
Label(root, text="Enter Aug Salary Amount: ").place(x=4, y=290)
Label(root, text="Enter Sep Salary Amount: ").place(x=4, y=310)
Label(root, text="Enter Oct Salary Amount: ").place(x=4, y=330)
Label(root, text="Enter Nov Salary Amount: ").place(x=4, y=350)
Label(root, text="Enter Dec Salary Amount: ").place(x=4, y=370)
# Month wise employee Leaves
Label(root, text="Enter Jan Leaves Amount: ").place(x=320, y=150)
Label(root, text="Enter Feb Leaves Amount: ").place(x=320, y=170)
Label(root, text="Enter March Leaves Amount: ").place(x=320, y=190)
Label(root, text="Enter April Leaves Amount: ").place(x=320, y=210)
Label(root, text="Enter May Leaves Amount: ").place(x=320, y=230)
Label(root, text="Enter June Leaves Amount: ").place(x=320, y=250)
Label(root, text="Enter July Leaves Amount: ").place(x=320, y=270)
Label(root, text="Enter Aug Leaves Amount: ").place(x=320, y=290)
Label(root, text="Enter Sep Leaves Amount: ").place(x=320, y=310)
Label(root, text="Enter Oct Leaves Amount: ").place(x=320, y=330)
Label(root, text="Enter Nov Leaves Amount: ").place(x=320, y=350)
Label(root, text="Enter Dec Leaves Amount: ").place(x=320, y=370)
# Month wise PT Amount
Label(root, text="Enter Jan PT Amount: ").place(x=620, y=150)
Label(root, text="Enter Feb PT Amount: ").place(x=620, y=170)
Label(root, text="Enter March PT Amount: ").place(x=620, y=190)
Label(root, text="Enter April PT Amount: ").place(x=620, y=210)
Label(root, text="Enter May PT Amount: ").place(x=620, y=230)
Label(root, text="Enter June PT Amount: ").place(x=620, y=250)
Label(root, text="Enter July PT Amount: ").place(x=620, y=270)
Label(root, text="Enter Aug PT Amount: ").place(x=620, y=290)
Label(root, text="Enter Sep PT Amount: ").place(x=620, y=310)
Label(root, text="Enter Oct PT Amount: ").place(x=620, y=330)
Label(root, text="Enter Nov PT Amount: ").place(x=620, y=350)
Label(root, text="Enter Dec PT Amount: ").place(x=620, y=370)
# Month wise paid salary
Label(root, text="Paid Jan Salary: ").place(x=920, y=150)
Label(root, text="", textvariable=PJS).place(x=1050, y=150)
Label(root, text="Paid Feb Salary: ").place(x=920, y=170)
Label(root, text="", textvariable=PFS).place(x=1050, y=170)
Label(root, text="Paid March Salary: ").place(x=920, y=190)
Label(root, text="", textvariable=PMAS).place(x=1050, y=190)
Label(root, text="Paid April Salary: ").place(x=920, y=210)
Label(root, text="", textvariable=PAPS).place(x=1050, y=210)
Label(root, text="Paid May Salary: ").place(x=920, y=230)
Label(root, text="", textvariable=PMYS).place(x=1050, y=230)
Label(root, text="Paid June Salary: ").place(x=920, y=250)
Label(root, text="", textvariable=PJUS).place(x=1050, y=250)
Label(root, text="Paid July Salary: ").place(x=920, y=270)
Label(root, text="", textvariable=PJYS).place(x=1050, y=270)
Label(root, text="Paid Aug Salary: ").place(x=920, y=290)
Label(root, text="", textvariable=PAS).place(x=1050, y=290)
Label(root, text="Paid Sep  Salary: ").place(x=920, y=310)
Label(root, text="", textvariable=PSS).place(x=1050, y=310)
Label(root, text="Paid Oct  Salary: ").place(x=920, y=330)
Label(root, text="", textvariable=POS).place(x=1050, y=330)
Label(root, text="Paid Nov Salary: ").place(x=920, y=350)
Label(root, text="", textvariable=PNS).place(x=1050, y=350)
Label(root, text="Paid Dec Salary: ").place(x=920, y=370)
Label(root, text="", textvariable=PDS).place(x=1050, y=370)
# printing details
# 4.Creating text boxes for employee details
E_N = Entry(root)
E_N.place(x=200, y=4)
ph_num = Entry(root)
ph_num.place(x=200, y=24)
E_D = Entry(root)
E_D.place(x=200, y=44)
E_E = Entry(root)
E_E.place(x=200, y=64)
E_I = Entry(root)
E_I.place(x=560, y=4)
E_Email = Entry(root)
E_Email.place(x=560, y=24)
E_A = Entry(root)
E_A.place(x=560, y=44)
E_Edu = Entry(root)
E_Edu.place(x=560, y=64)
# Entry of salary boxes
E_JAN_S = Entry(root)
E_JAN_S.place(x=160, y=150)
E_FEB_S = Entry(root)
E_FEB_S.place(x=160, y=170)
E_MAR_S = Entry(root)
E_MAR_S.place(x=160, y=190)
E_APR_S = Entry(root)
E_APR_S.place(x=160, y=210)
E_MAY_S = Entry(root)
E_MAY_S.place(x=160, y=230)
E_JUN_S = Entry(root)
E_JUN_S.place(x=160, y=250)
E_JUL_S = Entry(root)
E_JUL_S.place(x=160, y=270)
E_AUG_S = Entry(root)
E_AUG_S.place(x=160, y=290)
E_SEP_S = Entry(root)
E_SEP_S.place(x=160, y=310)
E_OCT_S = Entry(root)
E_OCT_S.place(x=160, y=330)
E_NOV_S = Entry(root)
E_NOV_S.place(x=160, y=350)
E_DEC_S = Entry(root)
E_DEC_S.place(x=160, y=370)
# Entry of montly leaves boxes
E_JAN_L = Entry(root)
E_JAN_L.place(x=480, y=150)
E_FEB_L = Entry(root)
E_FEB_L.place(x=480, y=170)
E_MAR_L = Entry(root)
E_MAR_L.place(x=480, y=190)
E_APR_L = Entry(root)
E_APR_L.place(x=480, y=210)
E_MAY_L = Entry(root)
E_MAY_L.place(x=480, y=230)
E_JUN_L = Entry(root)
E_JUN_L.place(x=480, y=250)
E_JUL_L = Entry(root)
E_JUL_L.place(x=480, y=270)
E_AUG_L = Entry(root)
E_AUG_L.place(x=480, y=290)
E_SEP_L = Entry(root)
E_SEP_L.place(x=480, y=310)
E_OCT_L = Entry(root)
E_OCT_L.place(x=480, y=330)
E_NOV_L = Entry(root)
E_NOV_L.place(x=480, y=350)
E_DEC_L = Entry(root)
E_DEC_L.place(x=480, y=370)
# Entry for PT Amount
E_JAN_PT = Entry(root)
E_JAN_PT.place(x=755, y=150)
E_FEB_PT = Entry(root)
E_FEB_PT.place(x=755, y=170)
E_MAR_PT = Entry(root)
E_MAR_PT.place(x=755, y=190)
E_APR_PT = Entry(root)
E_APR_PT.place(x=755, y=210)
E_MAY_PT = Entry(root)
E_MAY_PT.place(x=755, y=230)
E_JUN_PT = Entry(root)
E_JUN_PT.place(x=755, y=250)
E_JUL_PT = Entry(root)
E_JUL_PT.place(x=755, y=270)
E_AUG_PT = Entry(root)
E_AUG_PT.place(x=755, y=290)
E_SEP_PT = Entry(root)
E_SEP_PT.place(x=755, y=310)
E_OCT_PT = Entry(root)
E_OCT_PT.place(x=755, y=330)
E_NOV_PT = Entry(root)
E_NOV_PT.place(x=755, y=350)
E_DEC_PT = Entry(root)
E_DEC_PT.place(x=755, y=370)
# 5.Creating Button
Button(root, text="Submit", command=E_Details).place(x=700, y=590)
# Result which prints given details
# printing employee details:
Label(root, text="Employee Full Name:").place(x=4, y=470)
Label(root, text="", textvariable=rEn).place(x=150, y=470)
Label(root, text="Employee ID:").place(x=400, y=470)
Label(root, text="", textvariable=rIn).place(x=550, y=470)
Label(root, text="Employee Phone Number:").place(x=650, y=470)
Label(root, text="", textvariable=rPn).place(x=850, y=470)
Label(root, text="Employee Email:").place(x=1050, y=470)
Label(root, text="", textvariable=rEI).place(x=1160, y=470)
Label(root, text="Employee Department:").place(x=4, y=500)
Label(root, text="", textvariable=rEd).place(x=150, y=500)
Label(root, text="Employee Experience:").place(x=400, y=500)
Label(root, text="", textvariable=rEe).place(x=550, y=500)
Label(root, text="Employee Education:").place(x=650, y=500)
Label(root, text="", textvariable=rEdu).place(x=850, y=500)
Label(root, text="Employee Adderss:").place(x=1050, y=500)
Label(root, text="", textvariable=rEa).place(x=1160, y=500)
# Totals:
Label(root, text="Total Financial Amount:").place(x=4, y=620)
Label(root, text="", textvariable=rTFA).place(x=150, y=620)
Label(root, text="Total Number of Leaves:").place(x=400, y=620)
Label(root, text="", textvariable=rTL).place(x=550, y=620)
Label(root, text="Total PT Amount Debited:").place(x=650, y=620)
Label(root, text="", textvariable=rTPT).place(x=850, y=620)
Label(root, text="Total Paid Salary:").place(x=1050, y=620)
Label(root, text="", textvariable=rTPS).place(x=1150, y=620)
Label(root, text="TDS Percentage:").place(x=4, y=660)
Label(root, text="", textvariable=TDSP).place(x=150, y=660)
Label(root, text="TDS Amount:").place(x=400, y=660)
Label(root, text="", textvariable=TDSA).place(x=550, y=660)

mainloop()